In [13]:
# Recap: tóm tắt lại
# Pandas: là một thư viện mã nguồn mở được xây dựng dựa trên NumPy
# Pandas: để thao tác và phân tích dữ liệu

In [14]:
# NumPy: thư viện toán học, tính toán nhanh chóng trên các ma trận đa chiều nhanh hơn so với Core Python

In [15]:
import numpy as np

### Creating NumPy Arrays from Python Lists

In [16]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [17]:
[3.14, 4, 2, 3]

[3.14, 4, 2, 3]

In [18]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [19]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [20]:
a1 = np.array([1, 2, 3, 4])

In [21]:
type(a1)

numpy.ndarray

In [22]:
a2 = np.array([[1, 2, 3], 
              [4, 5, 6]])

In [23]:
type(a2)

numpy.ndarray

In [28]:
a2.shape

(2, 3)

In [29]:
a2.ndim #số chiều của array (array chứa 1 array khác -> 2 chiều)

2

In [32]:
a2.dtype

dtype('int32')

In [33]:
a2.size

6

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Creating NumPy Arrays from Scratch
### zeros, ones, full, arrange, linspace

In [37]:
# Shift + Tab: open Function Documents
np.zeros([2, 4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
# Create an array filled with a linear sequence
# Starting at 0, endingn at 20, stepping by 2
# (This is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
np.full((3, 5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [47]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random

In [74]:
# Seed for reproducibility
np.random.seed(0) # để mỗi lần random đều ra giá trị giống nhau

np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [97]:
np.random.rand(4, 4)

array([[0.05342718, 0.72559436, 0.01142746, 0.77058075],
       [0.14694665, 0.07952208, 0.08960303, 0.67204781],
       [0.24536721, 0.42053947, 0.55736879, 0.86055117],
       [0.72704426, 0.27032791, 0.1314828 , 0.05537432]])

In [85]:
np.random.normal(0, 1, (3,3))

array([[-1.17312341,  1.94362119, -0.41361898],
       [-0.74745481,  1.92294203,  1.48051479],
       [ 1.86755896,  0.90604466, -0.86122569]])

In [96]:
np.random.randint(0, 10, (4,5))

array([[3, 8, 4, 1, 4],
       [5, 0, 3, 1, 4],
       [4, 4, 0, 0, 8],
       [4, 6, 9, 3, 3]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Array Indexing & Slicing

#### One-dimensional subarray

In [105]:
x1 = np.random.randint(20, size=6)

In [106]:
x1[4], x1[0], x1[-1]

(10, 0, 19)

#### Multi-dimensional array

In [110]:
x2 = np.random.randint(10, size=(3, 4))

In [111]:
x2

array([[7, 2, 3, 9],
       [7, 6, 6, 2],
       [3, 6, 0, 8]])

In [120]:
x2[1, 2] = 5

In [121]:
x2

array([[7, 2, 3, 9],
       [7, 6, 5, 2],
       [3, 6, 0, 8]])

#### Slicing:
x[start:stop:step]

In [122]:
x1

array([ 0,  8, 19,  6, 10, 19])

In [125]:
x1[0:3]

array([ 0,  8, 19])

In [126]:
x1[2:4]

array([19,  6])

In [127]:
# every other element, every 2 step
x1[::2]

array([ 0, 19, 10])

In [128]:
x2

array([[7, 2, 3, 9],
       [7, 6, 5, 2],
       [3, 6, 0, 8]])

In [130]:
# two rows, three columns
x2[:2, :3]

array([[7, 2, 3],
       [7, 6, 5]])

In [131]:
x2[:2, :4]

array([[7, 2, 3, 9],
       [7, 6, 5, 2]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
### Reshaping of Arrays & Transpose

In [135]:
grid = np.arange(1, 10)
grid.shape

(9,)

In [141]:
grid.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
x = np.array([1, 2, 3])

In [142]:
x.shape

(3,)

In [146]:
x.reshape((1, 3)).shape

(1, 3)

In [151]:
x = np.array([[1., 7.], [3., 4.]])

In [152]:
x

array([[1., 7.],
       [3., 4.]])

In [153]:
x.T

array([[1., 3.],
       [7., 4.]])

### Array Concatenation (sự ghép nối) and Splitting

In [154]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [155]:
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [158]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
np.concatenate((grid, grid)) #axis = 0 by default

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [166]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [169]:
#vstack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], 
                [6, 5, 4]])
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [170]:
# horizontally stack the arrays: hstack
y = np.array([[99], [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

#### Splitting arrays

In [171]:
x = np.array([1, 2, 3, 99, 69, 3, 2, 1])

In [173]:
x1, x2, x3 = np.split(x, [3, 5])

In [174]:
x1

array([1, 2, 3])

In [177]:
x2

array([99, 69])

In [178]:
x3

array([3, 2, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

![image-broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [181]:
a = np.arange(3)

In [182]:
a

array([0, 1, 2])

In [183]:
a + 5 #Broadcasting

array([5, 6, 7])

In [185]:
b = np.ones((3, 3))

In [186]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [187]:
a.shape, b.shape

((3,), (3, 3))

In [188]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [189]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [191]:
c = np.arange(3).reshape((3, 1))

In [192]:
c

array([[0],
       [1],
       [2]])

In [193]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Manipulating & Comparing Arrays

In [196]:
list_number = [1, 2, 3]
ll = np.array(list_number)

In [199]:
ll

array([1, 2, 3])

In [200]:
sum(ll) # Python sum()

6

In [202]:
np.sum(ll) # NumPy sum() (faster)

6

In [214]:
# Create a massive (to lớn) NumPy array
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [215]:
%timeit sum(massive_array) # Python bulit-in function sum()
%timeit np.sum(massive_array) #  NumPy's np.sum()

479 μs ± 7.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
4.24 μs ± 92.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [216]:
np.mean(massive_array)


0.4978836855148755

In [217]:
np.max(massive_array)

0.9999484968692297

In [218]:
np.min(massive_array)

0.00019681476404465048

 ### Standard Deviation (độ lệch chuẩn) &  Variance (Phương sai)
 Link: https://www.mathsisfun.com/data/standard-deviation.html

In [220]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)

np.std(dog_height)

147.32277488562318

In [221]:
np.var(dog_height)

21704.0

In [223]:
np.sqrt(np.var(dog_height))

147.32277488562318

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Sorting Arrays
np.sorts uses an quicksort algorithm